# General
name: KIISS
description: "RSS Reader with Kii Backend"
url: http://localhost:4000

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: 
twitter: ardakaraduman
github: c0ze
google: 

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"

slim:
  pretty: true
