# General
name: KIISS
description: "RSS Reader with Kii Backend"
url: http://localhost:4000

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: 
twitter: ardakaraduman
github: c0ze
google: 

# Google Analytics
google_analytics_tracking_id: UA-56175514-4

slim:
  pretty: true
